[package]
name = "mq2lib"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
libc = "0.2"
log = "0.4"
simple-logging = "2.0"


[dependencies.windows]
version = "0.*"
features = [
	"Win32_Foundation",
	"Win32_System_SystemServices",
	"Win32_UI_WindowsAndMessaging",
]
